# Stage 1
FROM node:20.7.0 as node

WORKDIR /usr/src/app/site

COPY ./ ./

ARG FA_TOKEN

ENV FA_TOKEN=${FA_TOKEN}

RUN npm run docker:globals
RUN npm run docker:fa ${FA_TOKEN}
RUN npm run docker:install

EXPOSE 4200

CMD ["npm", "start"]
